server:
  port: 8080

spring:
  application:
    name: manga-novela-api

data:
  file:
    path: /home/zzoro/Desktop/dev/cursadas-POO/manga-novel-api/data/

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api/docs

logging:
  level:
    com.example.manga: INFO